dict={'Name':'Anurag','batch':'41'}
dict.pop('Name')
print(dict)
dict.clear()
print(dict)
tupexample=([1,1],'guru99')
print("the tuple before change",tupexample)
print("the id of tuple before change",id(tupexample))
tupexample=([1,1],'guru100')
print("the tuple after change",tupexample)
print("the id of tuple after change",id(tupexample))
